aliases:
  - &restore-npm-cache
    keys:
      - v3-dependencies-{{ checksum "package-lock.json" }}
      - v3-dependencies-master
      - v3-dependencies-
  - &restore-dist-cache
    keys:
      - v3-dist-{{ .Environment.CIRCLE_SHA1 }}
      - v3-dist-master
      - v3-dist-
  - &restore-ios-cache
    keys:
      - v3-dist-{{ .Environment.CIRCLE_SHA1 }}
      - v3-dist-master
      - v3-dist-

version: 2
jobs:
  install_dependencies:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache: *restore-npm-cache

      - run:
          name: Install Node modules
          command: npm i -ci

      - save_cache:
          key: v3-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  build-pwa:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache: *restore-npm-cache

      - run:
          name: Run linter
          command: npm run lint

      - run:
          name: Build BEEP
          command: npm run build

      - save_cache:
          key: v3-dist-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist

  sonarqube:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # SonarQube download, config and scanning
      - run: echo "Starting SonarQube scan"
      - run: wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
      - run: unzip sonar-scanner-cli-3.2.0.1227-linux.zip
      - run: echo "sonar.host.url=https://sonarcloud.io" > sonar-scanner-3.2.0.1227-linux/conf/sonar-scanner.properties
      - run: echo "sonar.login=$sonarqubekey" >> sonar-project.properties
      - run: echo "sonar.organization=$sonarorg" >> sonar-project.properties
      - run: sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner
      - run: echo "Scan complete, data sent to sonarcloud"

  build-ios:
    macos:
      xcode: '9.4.0'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache: *restore-npm-cache
      - restore_cache: *restore-dist-cache
      - run:
          name: Build iOS project
          command: npm run build-ios-ci
      - save_cache:
          key: v3-ios-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ios

 deploy-testflight:
    macos:
      xcode: '9.4.0'
    working_directory: ~/repo/ios/App
    steps:
      - restore_cache: *restore-ios-cache
      - run:
          name: Deploy to TestFlight
          command: fastline beta

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install_dependencies

      - build-pwa:
          requires: install_dependencies

      - build-ios:
          requires: install_dependencies
          # filters:
            # branches:
              # only: master

      - deploy-testflight:
          requires: build-ios
          # filters:
            # branches:
              # only: master

      - sonarqube
          # filters:
            # branches:
              # only: master
